### ISSUE TITLE
Prebuilt binaries?

### ISSUE THREAD

**Issue by oscarbg** [pal1000/swiftshader-dist-win#2]
Hi,
by pure luck just found your new project..
seems you already did a 0.1 release but with no binaries..
as I'm interested in trying that Vulkan CPU driver,
do you plan on adding prebuilt binaries to this or later releases?
thanks..

**Comment by pal1000** [comment]
A buildbot is planned for 1.0 release. I updated readme to make that clear.

**Comment by pal1000** [comment]
I managed to get unattended build working without much hassle. Now comes the tricky part. I have to setup a buildbot. It has to fetch both swiftshader and this repo sources and execute build jobs defined in this repo, either one  by one or in 2x2 parallel mode and collect and publish artifacts for each backend.

**Comment by oscarbg** [comment]
thanks for answering in such great detail! will keep open until 1.0..

**Comment by pal1000** [comment]
This is taking longer than expected due to limits Appveyor impposes:
- 60 minutes build timeout, but it can be bypassed with build matrix;
- 1GB cache limit;
- 2GB outgoing traffic limit.

**Comment by pal1000** [comment]
I had a very bad experience with AppVeyor;
- 60 minutes build timeout with SwiftShader needing 90 minutes to create a binary package;
- attempting to avoid timeout using build matrix didn't work because it is impossible to share cache between build matrix jobs;
- using temporary artifacts as cache between build matrix jobs is very hard to implement, confusing for users like you and I would hit another limit, 50 GB artifacts storage after about 250 builds or 4 months considering SwiftShader development pace,

I also tried Azure Pipelines but I didn't understand how to make it run my script. I don't know how MSYS2 got it's CI working there.  

Now I am using Github Actions if you haven't noticed. It is 1/3 faster than AppVeyor, and has a much higher build timeout of 6 hours. No way I'll hit that.
Unfortunately there have to be downsides here too:
- No UI for authoring CI jobs so I had to figure out the yaml syntax myself, fortunately is very well documented;
- Artifact publishing has some problems:
a.  actions/upload-artifact@v1 API cannot be used as it doesn't support single files and dynamic/volatile named artifacts;
b.  using bleeding edge actions/upload-artifact API fails bad with large artifacts - [1](https://github.com/pal1000/swiftshader-dist-win/runs/463512547?check_suite_focus=true), [2](https://github.com/actions/upload-artifact/pull/54#issuecomment-589752253), [3](https://github.com/actions/upload-artifact/pull/54#issuecomment-590207692).

**Comment by pal1000** [comment]
It looks like bleeding edge actions/upload-artifact API is even more busted than I thought. It looks like it fails to upload files over 1 chunk (4MB). I need a new plan.

**Comment by oscarbg** [comment]
thanks for keeping me updated and sad to hear so many issues!

**Comment by pal1000** [comment]
I figured out the stuff with Azure Pipelines. I should have used YAML configuration just like with Github Actions. Prebuilt binaries will be available [here](https://dev.azure.com/bontarka/swiftshader-dist-win/_build?view=runs). First binary package is already out.

Both platforms have problems that prevent me from having everything 100% fine, but Azure Pipelines has some pros that make the difference:
- it doesn't have artifacts larger than 4MB busted under any circumstances;
- it supports cache with schedule trigger which is a requirement for my skip build logic.

**Comment by pal1000** [comment]
I tagged 1.0. `#20200228.3 ` is the first binary package based on it.

**Comment by oscarbg** [comment]
Hi, thanks..
just a question why LLVM build is using "old" version 7.0.1 vs current 9.0.1..
"SwiftShader Device (LLVM 7.0.1)"..
can you switch LLVM versions easily or Google repo sets LLVM version to use?

PD:
I can close now..

**Comment by pal1000** [comment]
swiftshader uses a fork of LLVM with dedicated patches included in its reppository that's built along with it. So this is out of my control.

**Comment by oscarbg** [comment]
ok thanks.. didn't know..

**Comment by donizettilorenzo** [comment]
Up.

Can we have binaries for D3D8 and D3D9 too or we got to use the l"official" Legacy release?

**Comment by pal1000** [comment]
D3D8 and D3D9 support has been removed from Swiftshader master and moved in a [legacy branch](https://swiftshader.googlesource.com/SwiftShader/+/refs/heads/legacy-d3d9) that probably won't see updates, I'll make a legacy release with D3D8 and D3D9 only.

**Comment by pal1000** [comment]
@oscarbg, I noticed, based on commits pushed on [swiftshader repository](https://swiftshader.googlesource.com/SwiftShader/+log/refs/heads/master), that Google is working on upgrading LLVM reactor backend to LLVM 10. There is also [this issue](https://issuetracker.google.com/issues/152339534) (Google account required) tracking its progress.

**Comment by oscarbg** [comment]
@pal1000 thanks for noticing.. seems maybe already possible building on Windows as someone submitted a report: 
https://vulkan.gpuinfo.org/displayreport.php?id=8605

**Comment by pal1000** [comment]
@oscarbg, I tried, but swiftshader fails to find LLVM 10 headers despite LLVM 10 source code being included. If I have to build LLVM 10 manually I need to know which parts and more importantly the INSTALL_PREFIX, both pieces of information are unavailable.

**Comment by pal1000** [comment]
@oscarbg I'd like to move discussion about this in #4.
